// Generated by https://quicktype.io

export interface Credito {
    codigo_prestamo:       string;
    estado:                Estado;
    fecha_final_prestamo:  string;
    fecha_inicio_prestamo: string;
    id_cliente:            number;
    id_prestamo:           number;
    intereses:             number;
    meses_plazo:           number;
    num_cuotas:            number;
    valor_final_prestamo:  number;
    valor_prestamo:        number;
}

enum Estado {
    EnDeuda = "en deuda",
}
