// Generated by https://quicktype.io

export interface Factura {
    codigo_pago: string;
    estado:      Estado;
    fecha_pago:  string;
    id_pago:     number;
    id_prestamo: number;
    valor_pago:  number;
}

enum Estado {
    EnDeuda = "en deuda",
}
